/* ==========================================================================
   fp.js - front end for the Solar System Data Analysis project

   How the data gets here:
     1. Try the Flask API in app.py (which calls analysis.py).
     2. If the API is not running, fall back to the OFFLINE_DATA block below.

   The offline block was generated by running analysis.py, so both paths show
   the same numbers. That means the page still works if you just double-click
   index.html, but it demonstrates the real backend when app.py is running.
   ========================================================================== */

"use strict";

/* --------------------------------------------------------------------------
   1. Where to find the API
   -------------------------------------------------------------------------- */

// If this page was served by Flask, use the same origin. If it was opened as a
// file:// URL, guess the default local Flask port.
const API_BASE = location.protocol.startsWith("http")
  ? ""
  : "http://127.0.0.1:5000";

/* --------------------------------------------------------------------------
   2. Offline copy of the backend output (generated from analysis.py)
   -------------------------------------------------------------------------- */

const OFFLINE_DATA = {
    "planets": [
      {
        "name": "Mercury",
        "order": 1,
        "mass_kg": 3.301e+23,
        "mass_vs_earth": 0.055,
        "radius_km": 2439.7,
        "diameter_km": 4879,
        "distance_au": 0.387,
        "avg_temp_c": 167,
        "avg_temp_f": 333,
        "orbital_period_days": 88.0,
        "orbital_period_years": 0.24,
        "moons": 0,
        "density_kg_m3": 5427,
        "surface_gravity_m_s2": 3.7,
        "gravity_vs_earth": 0.38,
        "escape_velocity_km_s": 4.25,
        "classification": "Terrestrial"
      },
      {
        "name": "Venus",
        "order": 2,
        "mass_kg": 4.867e+24,
        "mass_vs_earth": 0.815,
        "radius_km": 6051.8,
        "diameter_km": 12104,
        "distance_au": 0.723,
        "avg_temp_c": 464,
        "avg_temp_f": 867,
        "orbital_period_days": 224.7,
        "orbital_period_years": 0.62,
        "moons": 0,
        "density_kg_m3": 5242,
        "surface_gravity_m_s2": 8.87,
        "gravity_vs_earth": 0.9,
        "escape_velocity_km_s": 10.36,
        "classification": "Terrestrial"
      },
      {
        "name": "Earth",
        "order": 3,
        "mass_kg": 5.972e+24,
        "mass_vs_earth": 1.0,
        "radius_km": 6371.0,
        "diameter_km": 12742,
        "distance_au": 1.0,
        "avg_temp_c": 15,
        "avg_temp_f": 59,
        "orbital_period_days": 365.25,
        "orbital_period_years": 1.0,
        "moons": 1,
        "density_kg_m3": 5513,
        "surface_gravity_m_s2": 9.82,
        "gravity_vs_earth": 1.0,
        "escape_velocity_km_s": 11.19,
        "classification": "Terrestrial"
      },
      {
        "name": "Mars",
        "order": 4,
        "mass_kg": 6.417e+23,
        "mass_vs_earth": 0.107,
        "radius_km": 3389.5,
        "diameter_km": 6779,
        "distance_au": 1.524,
        "avg_temp_c": -63,
        "avg_temp_f": -81,
        "orbital_period_days": 687.0,
        "orbital_period_years": 1.88,
        "moons": 2,
        "density_kg_m3": 3934,
        "surface_gravity_m_s2": 3.73,
        "gravity_vs_earth": 0.38,
        "escape_velocity_km_s": 5.03,
        "classification": "Terrestrial"
      },
      {
        "name": "Jupiter",
        "order": 5,
        "mass_kg": 1.898e+27,
        "mass_vs_earth": 317.816,
        "radius_km": 69911.0,
        "diameter_km": 139822,
        "distance_au": 5.203,
        "avg_temp_c": -108,
        "avg_temp_f": -162,
        "orbital_period_days": 4332.6,
        "orbital_period_years": 11.86,
        "moons": 95,
        "density_kg_m3": 1326,
        "surface_gravity_m_s2": 25.92,
        "gravity_vs_earth": 2.64,
        "escape_velocity_km_s": 60.2,
        "classification": "Gas giant"
      },
      {
        "name": "Saturn",
        "order": 6,
        "mass_kg": 5.683e+26,
        "mass_vs_earth": 95.161,
        "radius_km": 58232.0,
        "diameter_km": 116464,
        "distance_au": 9.537,
        "avg_temp_c": -139,
        "avg_temp_f": -218,
        "orbital_period_days": 10759.2,
        "orbital_period_years": 29.46,
        "moons": 146,
        "density_kg_m3": 687,
        "surface_gravity_m_s2": 11.19,
        "gravity_vs_earth": 1.14,
        "escape_velocity_km_s": 36.09,
        "classification": "Gas giant"
      },
      {
        "name": "Uranus",
        "order": 7,
        "mass_kg": 8.681e+25,
        "mass_vs_earth": 14.536,
        "radius_km": 25362.0,
        "diameter_km": 50724,
        "distance_au": 19.191,
        "avg_temp_c": -195,
        "avg_temp_f": -319,
        "orbital_period_days": 30688.5,
        "orbital_period_years": 84.02,
        "moons": 28,
        "density_kg_m3": 1270,
        "surface_gravity_m_s2": 9.01,
        "gravity_vs_earth": 0.92,
        "escape_velocity_km_s": 21.37,
        "classification": "Ice giant"
      },
      {
        "name": "Neptune",
        "order": 8,
        "mass_kg": 1.024e+26,
        "mass_vs_earth": 17.147,
        "radius_km": 24622.0,
        "diameter_km": 49244,
        "distance_au": 30.069,
        "avg_temp_c": -201,
        "avg_temp_f": -330,
        "orbital_period_days": 60195.0,
        "orbital_period_years": 164.8,
        "moons": 16,
        "density_kg_m3": 1638,
        "surface_gravity_m_s2": 11.27,
        "gravity_vs_earth": 1.15,
        "escape_velocity_km_s": 23.56,
        "classification": "Ice giant"
      }
    ],
    "summary": {
      "planet_count": 8,
      "metrics": [
        {
          "metric": "Diameter",
          "unit": "km",
          "min": {
            "planet": "Mercury",
            "value": 4879
          },
          "max": {
            "planet": "Jupiter",
            "value": 139822
          },
          "mean": 49094.75
        },
        {
          "metric": "Average temperature",
          "unit": "C",
          "min": {
            "planet": "Neptune",
            "value": -201
          },
          "max": {
            "planet": "Venus",
            "value": 464
          },
          "mean": -7.5
        },
        {
          "metric": "Distance from Sun",
          "unit": "AU",
          "min": {
            "planet": "Mercury",
            "value": 0.387
          },
          "max": {
            "planet": "Neptune",
            "value": 30.069
          },
          "mean": 8.45
        },
        {
          "metric": "Density",
          "unit": "kg/m3",
          "min": {
            "planet": "Saturn",
            "value": 687
          },
          "max": {
            "planet": "Earth",
            "value": 5513
          },
          "mean": 3129.62
        },
        {
          "metric": "Surface gravity",
          "unit": "m/s2",
          "min": {
            "planet": "Mercury",
            "value": 3.7
          },
          "max": {
            "planet": "Jupiter",
            "value": 25.92
          },
          "mean": 10.44
        },
        {
          "metric": "Moons",
          "unit": "count",
          "min": {
            "planet": "Mercury",
            "value": 0
          },
          "max": {
            "planet": "Saturn",
            "value": 146
          },
          "mean": 36.0
        }
      ]
    },
    "correlation": {
      "pearson_r": -0.634,
      "interpretation": "moderate negative (farther = colder) relationship",
      "trend_breakers": [
        {
          "planet": "Venus",
          "note": "Venus is warmer than Mercury despite being farther from the Sun"
        }
      ]
    }
  };

/* --------------------------------------------------------------------------
   3. Presentation-only extras
   Images and descriptions live here, not in planets_data.py, because that file
   is deliberately limited to raw measurements the analysis needs.
   -------------------------------------------------------------------------- */

const PLANET_META = {
  Mercury: {
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg",
    blurb: "The smallest planet and the closest to the Sun. With almost no atmosphere to trap heat, it swings from scorching day to freezing night — the largest temperature range of any planet."
  },
  Venus: {
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/PIA23791-Venus-RealAndEnhancedContrastViews-20200608_%28cropped%29.jpg",
    blurb: "Almost Earth's twin in size, but a thick carbon-dioxide atmosphere creates a runaway greenhouse effect. This makes Venus the hottest planet, even though Mercury is closer to the Sun."
  },
  Earth: {
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Ocean_world_Earth.jpg/500px-Ocean_world_Earth.jpg",
    blurb: "The densest planet in the Solar System and the only one known to hold liquid surface water. Every 'relative to Earth' figure on this page is measured against these values."
  },
  Mars: {
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png",
    blurb: "A cold desert world with iron-oxide dust giving it a red tint. Its low surface gravity — about a third of Earth's — falls directly out of its small mass and radius."
  },
  Jupiter: {
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Jupiter_OPAL_2024.png",
    blurb: "More massive than every other planet combined. Its huge mass produces the strongest surface gravity and by far the highest escape velocity in the Solar System."
  },
  Saturn: {
    image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Saturn_PIA06077.jpg",
    blurb: "Famous for its ring system, and the least dense planet of all — under 700 kg/m³, which is less dense than water. Saturn would float in a large enough ocean."
  },
  Uranus: {
    image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Uranus_Voyager2_color_calibrated.png",
    blurb: "An ice giant tipped roughly 98° on its side, so it effectively orbits on its rolling axis. It has the coldest recorded atmospheric temperature in the Solar System."
  },
  Neptune: {
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Neptune_Voyager2_color_calibrated.png",
    blurb: "The farthest planet from the Sun, with supersonic winds over 2,000 km/h. One Neptune year lasts about 165 Earth years."
  }
};

/* --------------------------------------------------------------------------
   4. Table configuration
   'derived' marks the columns analysis.py calculates rather than stores.
   -------------------------------------------------------------------------- */

const COLUMNS = [
  { key: "name",                 label: "Planet",         type: "text" },
  { key: "diameter_km",          label: "Diameter (km)",   type: "num" },
  { key: "mass_vs_earth",        label: "Mass (×Earth)", type: "num" },
  { key: "distance_au",          label: "Distance (AU)",   type: "num" },
  { key: "avg_temp_c",           label: "Avg temp (°C)", type: "num" },
  { key: "orbital_period_years", label: "Orbit (yr)",      type: "num", derived: true },
  { key: "density_kg_m3",        label: "Density (kg/m³)", type: "num", derived: true },
  { key: "surface_gravity_m_s2", label: "Gravity (m/s²)", type: "num", derived: true },
  { key: "escape_velocity_km_s", label: "Escape (km/s)",   type: "num", derived: true },
  { key: "moons",                label: "Moons",           type: "num" },
  { key: "classification",       label: "Type",            type: "text", derived: true }
];

/* --------------------------------------------------------------------------
   5. Small helpers
   -------------------------------------------------------------------------- */

// Thousands separators, but leave small decimals alone.
function fmt(value) {
  if (typeof value !== "number") return value;
  return Math.abs(value) >= 1000
    ? value.toLocaleString("en-US")
    : String(value);
}

// Colour temperature values so hot and cold read at a glance.
function tempClass(celsius) {
  if (celsius > 100) return "temp-hot";
  if (celsius < -50) return "temp-cold";
  return "";
}

// Escape text before it goes anywhere near innerHTML.
function esc(text) {
  return String(text).replace(/[&<>"']/g, function (ch) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch];
  });
}

/* --------------------------------------------------------------------------
   6. Load the data (API first, offline second)
   -------------------------------------------------------------------------- */

async function loadData() {
  const badge = document.getElementById("dataSource");

  try {
    // AbortController stops the page hanging if nothing is listening.
    const controller = new AbortController();
    const timer = setTimeout(function () { controller.abort(); }, 2500);

    const [planets, summary, correlation] = await Promise.all([
      fetch(API_BASE + "/api/planets",              { signal: controller.signal }).then(checkOk),
      fetch(API_BASE + "/api/analysis/summary",     { signal: controller.signal }).then(checkOk),
      fetch(API_BASE + "/api/analysis/correlation", { signal: controller.signal }).then(checkOk)
    ]);

    clearTimeout(timer);
    badge.textContent = "Live data from the Flask API (app.py)";
    badge.className = "badge badge-live";
    return { planets: planets, summary: summary, correlation: correlation };

  } catch (err) {
    badge.textContent = "Offline mode — using saved analysis.py output. "
                      + "Run “python3 app.py” for live API data.";
    badge.className = "badge badge-offline";
    return OFFLINE_DATA;
  }
}

function checkOk(response) {
  if (!response.ok) throw new Error("HTTP " + response.status);
  return response.json();
}

/* --------------------------------------------------------------------------
   7. Render: the selected planet
   -------------------------------------------------------------------------- */

function renderPlanetCard(planet) {
  const meta = PLANET_META[planet.name] || { image: "", blurb: "" };

  // [label, value, isDerived]
  const rows = [
    ["Position from the Sun", planet.order + " of 8", false],
    ["Diameter", fmt(planet.diameter_km) + " km", false],
    ["Mass", planet.mass_vs_earth + " × Earth", false],
    ["Distance from the Sun", planet.distance_au + " AU", false],
    ["Average temperature", fmt(planet.avg_temp_c) + " °C ("
                            + fmt(planet.avg_temp_f) + " °F)", false],
    ["Orbital period", fmt(planet.orbital_period_days) + " days ("
                       + planet.orbital_period_years + " yr)", true],
    ["Density", fmt(planet.density_kg_m3) + " kg/m³", true],
    ["Surface gravity", planet.surface_gravity_m_s2 + " m/s² ("
                        + planet.gravity_vs_earth + " × Earth)", true],
    ["Escape velocity", planet.escape_velocity_km_s + " km/s", true],
    ["Moons", fmt(planet.moons), false]
  ];

  const bodyHtml = rows.map(function (row) {
    const cls = row[2] ? ' class="derived"' : "";
    return "<tr><th scope=\"row\">" + esc(row[0]) + "</th>"
         + "<td" + cls + ">" + esc(row[1]) + "</td></tr>";
  }).join("");

  document.getElementById("planetCard").innerHTML =
      '<img src="' + esc(meta.image) + '" alt="' + esc(planet.name) + '" '
    +     'loading="lazy" '
    +     'onerror="this.style.visibility=\'hidden\'">'
    + "<div>"
    +   "<h3>" + esc(planet.name) + "</h3>"
    +   '<p class="planet-meta">'
    +     '<span class="tag">' + esc(planet.classification) + "</span>"
    +     '<span class="tag">Planet ' + planet.order + "</span>"
    +   "</p>"
    +   '<p class="blurb">' + esc(meta.blurb) + "</p>"
    +   '<table class="stat-table">'
    +     "<caption>Values in bold are calculated by <code>analysis.py</code> "
    +     "from mass and radius.</caption>"
    +     "<tbody>" + bodyHtml + "</tbody>"
    +   "</table>"
    + "</div>";

  // Keep the big table's highlight in step with the dropdown.
  document.querySelectorAll("#allTable tbody tr").forEach(function (tr) {
    tr.classList.toggle("is-selected", tr.dataset.planet === planet.name);
  });
}

/* --------------------------------------------------------------------------
   8. Render: the all-planets table (sortable)
   -------------------------------------------------------------------------- */

let sortState = { key: "order", asc: true };

function renderTable(planets) {
  const table = document.getElementById("allTable");

  const sorted = planets.slice().sort(function (a, b) {
    const va = a[sortState.key];
    const vb = b[sortState.key];
    if (va < vb) return sortState.asc ? -1 : 1;
    if (va > vb) return sortState.asc ? 1 : -1;
    return 0;
  });

  // --- head ---
  table.tHead.innerHTML = "<tr>" + COLUMNS.map(function (col) {
    const active = sortState.key === col.key;
    const arrow = active ? (sortState.asc ? " ▲" : " ▼") : "";
    return '<th tabindex="0" role="button" data-key="' + col.key + '"'
         + ' aria-sort="' + (active ? (sortState.asc ? "ascending" : "descending") : "none") + '"'
         + (col.derived ? ' class="derived-key"' : "") + ">"
         + esc(col.label) + '<span class="arrow">' + arrow + "</span></th>";
  }).join("") + "</tr>";

  // --- body ---
  table.tBodies[0].innerHTML = sorted.map(function (p) {
    const cells = COLUMNS.map(function (col) {
      const raw = p[col.key];
      if (col.key === "name") {
        return '<td class="planet-name">' + esc(raw) + "</td>";
      }
      const classes = [];
      if (col.derived) classes.push("derived");
      if (col.key === "avg_temp_c") classes.push(tempClass(raw));
      const attr = classes.filter(Boolean).length
        ? ' class="' + classes.filter(Boolean).join(" ") + '"'
        : "";
      return "<td" + attr + ">" + esc(fmt(raw)) + "</td>";
    }).join("");
    return '<tr data-planet="' + esc(p.name) + '">' + cells + "</tr>";
  }).join("");

  // Sorting: click or keyboard on a heading.
  table.tHead.querySelectorAll("th").forEach(function (th) {
    function activate() {
      const key = th.dataset.key;
      // New column starts descending for numbers, ascending for text.
      if (sortState.key === key) {
        sortState.asc = !sortState.asc;
      } else {
        const col = COLUMNS.find(function (c) { return c.key === key; });
        sortState = { key: key, asc: col.type === "text" };
      }
      renderTable(planets);
      syncSelection();
    }
    th.addEventListener("click", activate);
    th.addEventListener("keydown", function (e) {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); activate(); }
    });
  });

  // Clicking a row moves the dropdown to that planet.
  table.tBodies[0].querySelectorAll("tr").forEach(function (tr) {
    tr.addEventListener("click", function () {
      const select = document.getElementById("planetSelect");
      select.value = tr.dataset.planet;
      select.dispatchEvent(new Event("change"));
    });
  });
}

function syncSelection() {
  const name = document.getElementById("planetSelect").value;
  document.querySelectorAll("#allTable tbody tr").forEach(function (tr) {
    tr.classList.toggle("is-selected", tr.dataset.planet === name);
  });
}

/* --------------------------------------------------------------------------
   9. Render: the correlation finding
   -------------------------------------------------------------------------- */

function renderCorrelation(correlation, summary) {
  const outliers = (correlation.trend_breakers || []).map(function (o) {
    return '<p class="outlier"><strong>Trend breaker:</strong> ' + esc(o.note)
         + ". A thick carbon-dioxide atmosphere traps heat, so distance alone "
         + "does not decide temperature.</p>";
  }).join("");

  const tempStat = (summary.metrics || []).find(function (m) {
    return m.metric === "Average temperature";
  });

  const spread = tempStat
    ? "<p>Across the eight planets the average temperature ranges from "
      + esc(fmt(tempStat.min.value)) + " °C on " + esc(tempStat.min.planet)
      + " to " + esc(fmt(tempStat.max.value)) + " °C on " + esc(tempStat.max.planet)
      + ", with a mean of " + esc(fmt(tempStat.mean)) + " °C.</p>"
    : "";

  document.getElementById("correlation").innerHTML =
      '<p><span class="r-value">r = ' + esc(correlation.pearson_r) + "</span></p>"
    + "<p>Pearson correlation between distance from the Sun and average "
    + "temperature: a <strong>" + esc(correlation.interpretation) + "</strong>.</p>"
    + spread
    + outliers;
}

/* --------------------------------------------------------------------------
   10. Dark-mode toggle
   -------------------------------------------------------------------------- */

function setupThemeToggle() {
  const btn = document.getElementById("themeToggle");
  if (!btn) return;
  const root = document.documentElement;   // <html>; matches the CSS + head script

  function sync() {
    const isDark = root.classList.contains("dark");
    btn.textContent = isDark ? "Light mode" : "Dark mode";
    btn.setAttribute("aria-pressed", String(isDark));
  }

  btn.addEventListener("click", function () {
    const isDark = root.classList.toggle("dark");
    try { localStorage.setItem("theme", isDark ? "dark" : "light"); } catch (e) {}
    sync();
  });

  sync();   // label the button to match the theme applied by the head script
}

function setupColorToggle() {
  const btn = document.getElementById("colorToggle");
  if (!btn) return;
  const root = document.documentElement;

  function sync() {
    const inColor = root.classList.contains("color-images");
    btn.textContent = inColor ? "Grayscale images" : "Color images";
    btn.setAttribute("aria-pressed", String(inColor));
  }

  btn.addEventListener("click", function () {
    const inColor = root.classList.toggle("color-images");
    try { localStorage.setItem("images", inColor ? "color" : "grayscale"); } catch (e) {}
    sync();
  });

  sync();   // label to match whatever the head script already applied
}

/* --------------------------------------------------------------------------
   11. Start up
   -------------------------------------------------------------------------- */

async function init() {
  setupThemeToggle();              // wire this first so it works immediately,
                                   // without waiting on the data fetch
  setupColorToggle();
  const data = await loadData();
  const planets = data.planets;

  // Build the dropdown from the data so the two can never disagree.
  const select = document.getElementById("planetSelect");
  select.innerHTML = planets
    .slice()
    .sort(function (a, b) { return a.order - b.order; })
    .map(function (p) {
      return '<option value="' + esc(p.name) + '">'
           + p.order + ". " + esc(p.name) + "</option>";
    }).join("");

  const byName = {};
  planets.forEach(function (p) { byName[p.name] = p; });

  select.addEventListener("change", function () {
    renderPlanetCard(byName[this.value]);
  });

  renderTable(planets);
  select.value = "Earth";           // a familiar starting point
  renderPlanetCard(byName["Earth"]);
  renderCorrelation(data.correlation, data.summary);
}

document.addEventListener("DOMContentLoaded", init);
